/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mychic_vimglasses_VimGlasses */

#ifndef _Included_com_homage_matting_Matting
#define _Included_com_homage_matting_Matting

#ifdef __cplusplus
extern "C" {
#endif


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_openLog
  (JNIEnv * env, jclass c, jstring logFileStr );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_closeLog
  (JNIEnv * env, jclass c );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_setDumpDir
	(JNIEnv * env, jclass c, jstring jinFile );



/*
 * Class:     com_mychic_vimglasses_VimGlasses
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_init
  (JNIEnv *, jclass, jstring jprmFile, jstring jsideFile, jint width, jint height );



JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_initCamera
	(JNIEnv * env, jclass c, jint orientation );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_setBackground
	(JNIEnv * env, jclass c, jstring jinFile );



JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_setFrameRate
	(JNIEnv * env, jclass c, jint frameRate );


JNIEXPORT jint JNICALL  Java_com_homage_matting_Matting_cameraCallBack
		(JNIEnv * env, jclass c, jint width, jint height, jbyteArray buffer );


JNIEXPORT jint JNICALL  Java_com_homage_matting_Matting_process
	(JNIEnv * env, jclass c, jint width, jint height, jbyteArray buffer );


JNIEXPORT int JNICALL Java_com_homage_matting_Matting_getUpdate
		(JNIEnv * env, jclass c, jbyteArray  out, jbyteArray  out1 );



JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_start
		(JNIEnv * env, jclass c, jint operation );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_stop
		(JNIEnv * env, jclass c, jint operation );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_setOperation
		(JNIEnv * env, jclass c, jint operation );





JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_setColor
		(JNIEnv * env, jclass c, jint color );


JNIEXPORT jint JNICALL  Java_com_homage_matting_Matting_setBackgound
	(JNIEnv * env, jclass c, jint width, jint height, jbyteArray buffer );





JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_startRecord
	(JNIEnv * env, jclass c, jstring jdir );


JNIEXPORT jint JNICALL Java_com_homage_matting_Matting_stopRecord
	(JNIEnv * env, jclass c );


#ifdef __cplusplus
}
#endif
#endif
