/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mychic_vimglasses_VimGlasses */

#ifndef _Included_com_homage_matting_Matting2
#define _Included_com_homage_matting_Matting2

#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_mychic_vimglasses_VimGlasses
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_create(JNIEnv *, jclass, jstring, jstring, jint, jint);

JNIEXPORT jint JNICALL  Java_com_homage_matting_Matting2_delete(JNIEnv *, jclass, jint);

JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_prepareYUV
        (JNIEnv *env, jclass c, jint iM, jbyteArray buffer, jint width, jint height, jint orientation, jbyteArray resRGBImage);

JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_prepareRGB
        (JNIEnv *env, jclass c, jint iM, jbyteArray buffer, jint width, jint height, jbyteArray resRGBImage);

JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_inspect
        (JNIEnv *env, jclass c, jint iM);

JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_getBackgroundSimilarity
        (JNIEnv *env, jclass c, jint iM);

JNIEXPORT jint JNICALL Java_com_homage_matting_Matting2_process
        (JNIEnv *env, jclass c, jint iM, jbyteArray resMaskChannel);


#ifdef __cplusplus
}
#endif
#endif
